### ISSUE TITLE
Changing severity classes

### ISSUE THREAD

**Issue by ghost** [ahebrank/emergency_alerts#2]
Is it possible to change the classes for the severity of the alert (e.g. `.announcement`)? I'm working on a project that requires BEM classes, so rather than `.announcement`, it'd have to be `.emergency-alert--announcement`. A pain, I know!

**Comment by ahebrank** [comment]
If you override the [template](https://github.com/ahebrank/emergency_alerts/blob/8.x-2.x/templates/emergency-alert.html.twig) in your theme, here's a quick tweak:

```
{%
  set classes = [
    'emergency-alert',
    'emergency-alert--' ~ alert_level,
    (alert_level == 'announcement')? 'closeable'
  ]
%}
```

We'll pretty much always override this template depending on what front end framework provides the alert styling.

**Comment by ghost** [comment]
D'oh — trust me to miss that! Thanks, Andy.
